const core = @import("../index.zig");
const makeCoord = core.geometry.makeCoord;
const Action = core.protocol.Action;

pub fn beatLevelActions(level_number: usize) []const Action {
    return switch (level_number) {

        // Single enemy
        0 => comptime &[_]Action{
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .attack = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .attack = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // Multiple enemies
        1 => comptime &[_]Action{
            Action{ .move = makeCoord(0, 1) },
            Action{ .attack = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .attack = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // Archer in narrow hallway.
        2 => comptime &[_]Action{
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .attack = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .kick = makeCoord(1, 0) },
            Action{ .attack = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .attack = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // Flanked by archers
        3 => comptime &[_]Action{
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // Wall of archers
        4 => comptime &[_]Action{
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .wait = {} },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .wait = {} },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // Single kagaroo
        5 => comptime &[_]Action{
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(0, 1) },
        },

        // Invincible enemies
        6 => comptime &[_]Action{
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .kick = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .kick = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // Invincible enemies and an archer
        7 => comptime &[_]Action{
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .kick = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .kick = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .attack = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .attack = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // Charging enemy and lava
        8 => comptime &[_]Action{
            Action{ .wait = {} },
            Action{ .wait = {} },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // Charging enemy and an archer
        9 => comptime &[_]Action{
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .wait = {} },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .attack = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // Invicible enmies and a charging enemy
        10 => comptime &[_]Action{
            Action{ .kick = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .wait = {} },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .attack = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // Archer guarding chokepoint
        11 => comptime &[_]Action{
            Action{ .move = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .attack = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .attack = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .attack = makeCoord(1, 0) },
            Action{ .attack = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .kick = makeCoord(-1, 0) },
            Action{ .wait = {} },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // You're the archer now!
        12 => comptime &[_]Action{
            Action{ .move = makeCoord(0, 1) },
            Action{ .attack = makeCoord(1, 0) },
            Action{ .attack = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        // Whose side are you on?
        13 => comptime &[_]Action{
            Action{ .attack = makeCoord(0, 1) },
            Action{ .attack = makeCoord(0, 1) },
            Action{ .attack = makeCoord(0, 1) },
            Action{ .attack = makeCoord(0, -1) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .move = makeCoord(0, 1) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .attack = makeCoord(-1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .attack = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(0, -1) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
            Action{ .move = makeCoord(1, 0) },
        },

        else => &[_]Action{},
    };
}
