const core = @import("../index.zig");
const makeCoord = core.geometry.makeCoord;
const Action = core.protocol.Action;

pub const beat_level_actions = [_][]const Action{

    // Single enemy
    &[_]Action{
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Multiple enemies
    &[_]Action{
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Archer in narrow hallway.
    &[_]Action{
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(1, 0) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Flanked by archers
    &[_]Action{
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Wall of archers
    &[_]Action{
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Single kagaroo
    &[_]Action{
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
    },

    // Invincible enemies
    &[_]Action{
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .kick = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .kick = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Invincible enemies and an archer
    &[_]Action{
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Charging enemy and lava
    &[_]Action{
        Action{ .wait = {} },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Charging enemy and an archer
    &[_]Action{
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Invicible enmies and a charging enemy
    &[_]Action{
        Action{ .kick = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Archer guarding chokepoint
    &[_]Action{
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(-1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Some blob
    &[_]Action{
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
Action{ .move = makeCoord(1, 0) },
Action{ .move = makeCoord(1, 0) },
Action{ .wait = {} },
Action{ .move = makeCoord(0, -1) },
Action{ .wait = {} },
Action{ .move = makeCoord(0, 1) },
Action{ .wait = {} },
Action{ .move = makeCoord(-1, 0) },
Action{ .move = makeCoord(1, 0) },
Action{ .move = makeCoord(1, 0) },
Action{ .move = makeCoord(1, 0) },
Action{ .move = makeCoord(1, 0) },
    },

    // Blob and other enemies
    &[_]Action{
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Blob and incinvible enemies
    &[_]Action{
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(0, -1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, 1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // You're the archer now!
    &[_]Action{
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Whose side are you on?
    &[_]Action{
        Action{ .attack = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },
};
