const core = @import("../index.zig");
const makeCoord = core.geometry.makeCoord;
const Action = core.protocol.Action;

pub const beat_level_actions = [_][]const Action{

    // Single enemy
    &[_]Action{
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Multiple enemies
    &[_]Action{
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Archer in narrow hallway.
    &[_]Action{
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(1, 0) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Flanked by archers
    &[_]Action{
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Wall of archers
    &[_]Action{
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Kagaroo
    &[_]Action{
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
    },

    // Invincible enemies
    &[_]Action{
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .kick = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .kick = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Invincible enemies and an archer
    &[_]Action{
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Rhino and lava
    &[_]Action{
        Action{ .wait = {} },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Rhino and archer
    &[_]Action{
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Invicible enmies and a rhino
    &[_]Action{
        Action{ .kick = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Archer guarding a chokepoint
    &[_]Action{
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(-1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Some blobs
    &[_]Action{
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, 1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Blob and other enemies
    &[_]Action{
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Blob and incinvible enemies
    &[_]Action{
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(0, -1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, 1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, 1) },
        Action{ .kick = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // You're the archer now!
    &[_]Action{
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Whose side are you on?
    &[_]Action{
        Action{ .attack = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, 1) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .attack = makeCoord(-1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .attack = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Kangaroos can't attack
    &[_]Action{
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .kick = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .kick = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .kick = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Blobs can't see
    &[_]Action{
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .grow = makeCoord(0, 1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, 1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(-1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(-1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, 1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, 1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .wait = {} },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, 1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(-1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(-1, 0) },
        Action{ .shrink = 0 },
        Action{ .wait = {} },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(-1, 0) },
        Action{ .wait = {} },
        Action{ .shrink = 1 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
    },

    // Learn to charge
    &[_]Action{
        Action{ .move = makeCoord(1, 0) },
        Action{ .fast_move = makeCoord(2, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .fast_move = makeCoord(2, 0) },
        Action{ .fast_move = makeCoord(2, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .fast_move = makeCoord(0, -2) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .fast_move = makeCoord(0, 2) },
        Action{ .fast_move = makeCoord(0, 2) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .fast_move = makeCoord(0, -2) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .fast_move = makeCoord(2, 0) },
        Action{ .fast_move = makeCoord(2, 0) },
        Action{ .move = makeCoord(0, -1) },
    },

    // Look how you've grown
    &[_]Action{
        Action{ .fast_move = makeCoord(0, -2) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .fast_move = makeCoord(2, 0) },
        Action{ .fast_move = makeCoord(2, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, 1) },
        Action{ .fast_move = makeCoord(0, 2) },
        Action{ .fast_move = makeCoord(0, 2) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .fast_move = makeCoord(-2, 0) },
        Action{ .fast_move = makeCoord(-2, 0) },
        Action{ .shrink = 1 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .move = makeCoord(0, 1) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .attack = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Not for you
    &[_]Action{
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, -1) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .wait = {} },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },

    // Turtles can't kick
    &[_]Action{
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(-1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, -1) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .fast_move = makeCoord(-2, 0) },
        Action{ .move = makeCoord(-1, 0) },
        Action{ .fast_move = makeCoord(-2, 0) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(0, 1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .fast_move = makeCoord(2, 0) },
        Action{ .fast_move = makeCoord(2, 0) },
        Action{ .fast_move = makeCoord(2, 0) },
        Action{ .move = makeCoord(0, -1) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .shrink = 0 },
        Action{ .grow = makeCoord(0, 1) },
        Action{ .shrink = 0 },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
        Action{ .move = makeCoord(1, 0) },
    },
};
